# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 649)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:  #0a4382;\n"
"\n"
"QFrame {\n"
"    border: none;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(400, 0))
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/assets/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btnBox = QtWidgets.QGroupBox(self.sidebar)
        self.btnBox.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"")
        self.btnBox.setTitle("")
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.btnBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Historial_btn = QtWidgets.QPushButton(self.btnBox)
        self.Historial_btn.setObjectName("Historial_btn")
        self.verticalLayout.addWidget(self.Historial_btn)
        self.Camara_btn = QtWidgets.QPushButton(self.btnBox)
        self.Camara_btn.setObjectName("Camara_btn")
        self.verticalLayout.addWidget(self.Camara_btn)
        self.verticalLayout_2.addWidget(self.btnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.sidebar)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setStyleSheet("QFrame {\n"
"    border: none;\n"
"}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setStyleSheet("QWidget {\n"
"backgroun-color: rgb(255,255,255)\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.camara_page = QtWidgets.QWidget()
        self.camara_page.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.camara_page.setObjectName("camara_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.camara_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget.addWidget(self.camara_page)
        self.historial_page = QtWidgets.QWidget()
        self.historial_page.setObjectName("historial_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.historial_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Date_frame = QtWidgets.QFrame(self.historial_page)
        self.Date_frame.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Date_frame.setObjectName("Date_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Date_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.Date_frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.frame = QtWidgets.QFrame(self.Date_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.before_dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.before_dateTimeEdit.setObjectName("before_dateTimeEdit")
        self.verticalLayout_7.addWidget(self.before_dateTimeEdit)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.after_dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.frame_3)
        self.after_dateTimeEdit_2.setObjectName("after_dateTimeEdit_2")
        self.verticalLayout_8.addWidget(self.after_dateTimeEdit_2)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.Date_frame)
        self.table_frame = QtWidgets.QFrame(self.historial_page)
        self.table_frame.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame.setObjectName("table_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.table_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(self.table_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    alternating-row-colors: true;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: white;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #f0f0f0; /* Color gris claro */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #2980B9;  /* Color de fondo de la celda seleccionada */\n"
"    color: #ffffff;  /* Color del texto de la celda seleccionada */\n"
"}\n"
"\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.table_frame)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 8)
        self.stackedWidget.addWidget(self.historial_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.main_frame)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Historial_btn.setText(_translate("MainWindow", "Historial"))
        self.Camara_btn.setText(_translate("MainWindow", "Camara"))
        self.label_2.setText(_translate("MainWindow", "· Filtar por fecha:"))
        self.label_3.setText(_translate("MainWindow", "- Después de:"))
        self.label_4.setText(_translate("MainWindow", "- Antes de:"))
import resources_rc
